apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090 # Địa chỉ server Prometheus trong mạng Docker
    isDefault: true # Đặt làm datasource mặc định

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100 # Địa chỉ server Loki (Logs)

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200 # Địa chỉ server Tempo (Tracing)
