global:
  scrape_interval: 10s # Prometheus sẽ "quét" (pull) metrics mỗi 10 giây một lần
  evaluation_interval: 10s # Khoảng thời gian tính toán rule (alert, record) mỗi 10 giây

scrape_configs:
  - job_name: 'api-gateway' # Tên job, thường đặt theo tên service
    metrics_path: '/actuator/prometheus' # Đường dẫn để lấy metrics từ Spring Boot Actuator
    static_configs:
      - targets: ['api-gateway:8080'] # Host và Port của service (tên phải khớp với service name trong docker-compose)

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['account-service:8082']

  - job_name: 'menu-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['menu-service:8083']

  - job_name: 'audit-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['audit-service:8084']
